auth_enabled: false

server:
  http_listen_port: 3100
# Read timeout for HTTP server
  http_server_read_timeout: 3m
# Write timeout for HTTP server
  http_server_write_timeout: 3m
common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: ./tmp
  storage:
    filesystem:
      chunks_directory: ./tmp/chunks
      rules_directory: ./tmp/loki/rules

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

query_range:
  split_queries_by_interval: 0
  parallelise_shardable_queries: false

querier:
  max_concurrent: 2048

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true

ruler:
  alertmanager_url: http://172.18.249.190:9093
